version: '3.8'

services:
  app:
    image: dingyufei/goofish-monitor:latest
    container_name: ai-goofish-monitor-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
