name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude-code-action:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@claude'))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Prepare Environment
        run: |
          # Install Bun
          curl -fsSL https://bun.sh/install | bash
          # Create config directory
          mkdir -p $HOME/.claude-code-router
          # Create config file
          cat << 'EOF' > $HOME/.claude-code-router/config.json
          {
            "log": true,
            "NON_INTERACTIVE_MODE": true,
            "OPENAI_API_KEY": "${{ secrets.OPENAI_API_KEY }}",
            "OPENAI_BASE_URL": "https://api.deepseek.com",
            "OPENAI_MODEL": "deepseek-chat"
          }
          EOF
        shell: bash

      - name: Start Claude Code Router
        run: |
          # Start the router in the background and log output to nohup.out
          nohup ~/.bun/bin/bunx @musistudio/claude-code-router@1.0.8 start &
        shell: bash

      # ⬇️ --- 新增的诊断步骤 --- ⬇️

      - name: 🧐 Diagnose Network and Service
        run: |
          echo "--- Waiting for the router to start up... ---"
          sleep 5 # 等待5秒，确保代理服务有足够时间启动

          echo "--- Checking router logs (nohup.out) for errors... ---"
          cat nohup.out || echo "nohup.out not found or is empty."

          echo "--- Checking if the port 3456 is listening... ---"
          # 使用 ss 命令检查端口是否被监听
          ss -tulpn | grep 3456 || echo "Port 3456 is not in use. The router may have failed to start."

          echo "--- Testing connectivity from runner to DeepSeek API... ---"
          # 使用 curl 的 verbose 模式测试外部连接，-m 15 设置15秒超时
          curl -v -m 15 https://api.deepseek.com/v1/models || echo "Failed to connect to api.deepseek.com"

      # ⬆️ --- 诊断步骤结束 --- ⬆️

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        env:
          ANTHROPIC_BASE_URL: http://localhost:3456
        with:
          timeout_minutes: "10" # 可以适当缩短超时，方便更快看到结果
          anthropic_api_key: "any-string-is-ok"
