name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude-code-action:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@claude'))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Prepare Environment
        run: |

          curl -fsSL https://bun.sh/install | bash

          mkdir -p $HOME/.claude-code-router

          cat << 'EOF' > $HOME/.claude-code-router/config.json
          {
              "log": true,
              "NON_INTERACTIVE_MODE": true,
              "API_TIMEOUT_MS": 600000,
              "Providers": [
                  {
                      "name": "modelscope",
                      "api_base_url": "https://api-inference.modelscope.cn/v1/chat/completions",
                      "api_key": "${{ secrets.OPENAI_API_KEY }}",
                      "models": [
                          "Qwen/Qwen3-Coder-480B-A35B-Instruct",
                          "Qwen/Qwen3-235B-A22B-Thinking-2507"
                      ],
                      "transformer": {
                          "use": [
                              [
                                  "maxtoken",
                                  {
                                      "max_tokens": 65536
                                  }
                              ],
                              "enhancetool"
                          ],
                          "Qwen/Qwen3-235B-A22B-Thinking-2507": {
                              "use": [
                                  "reasoning"
                              ]
                          }
                      }
                  },
                  {
                      "name": "gemini",
                      "api_base_url": "https://generativelanguage.googleapis.com/v1beta/models/",
                      "api_key": "${{ secrets.GEMINI_API_KEY }}",
                      "models": [
                          "gemini-2.5-flash",
                          "gemini-2.5-pro"
                      ],
                      "transformer": {
                          "use": [
                              "gemini"
                          ]
                      }
                  }
              ],
              "Router": {
                  "default": "modelscope,Qwen/Qwen3-Coder-480B-A35B-Instruct",
                  "background": "modelscope,Qwen/Qwen3-Coder-480B-A35B-Instruct",
                  "think": "modelscope,Qwen/Qwen3-235B-A22B-Thinking-2507",
                  "longContext": "modelscope,Qwen/Qwen3-Coder-480B-A35B-Instruct",
                  "longContextThreshold": 60000,
                  "webSearch": "gemini,gemini-2.5-flash"
              }
          }
          EOF
        shell: bash

      - name: Start Claude Code Router
        run: |
          nohup ~/.bun/bin/bunx @musistudio/claude-code-router@1.0.8 start &
        shell: bash

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        env:
          ANTHROPIC_BASE_URL: http://localhost:3456
        with:

          anthropic_api_key: "any-string-is-ok"
